hpfn/charcoallog

charcoallog/investments/templates/investments/detail.html

Detail page with data from investments home only.

---

.gitignore
charcoallog/__init__.py
charcoallog/celery.py
charcoallog/core/scrap_line3_service.py
charcoallog/core/tasks.py
charcoallog/settings.py

Use Celery to webscrapping task scheduling

---

charcoallog/core/scrap_line3_service.py
charcoallog/core/tasks.py
charcoallog/core/tests/ibov.html
charcoallog/core/tests/ipca.html
charcoallog/core/tests/selic.html
charcoallog/core/tests/test_scraping_bs4_line3.py

DRY - tasks and scrap_line3_service - core app

---

charcoallog/bank/static/ajax_core.js
charcoallog/bank/templates/bank/frameset_pages/line1.html
charcoallog/bank/tests/test_view_update.py
charcoallog/bank/views.py

Allow user create an account by update

---

charcoallog/bank/static/ajax_core.js
charcoallog/bank/templates/bank/frameset_pages/line1.html

Remove empty <li> - html tag

---

requirements.txt

Update billiard to 3.5.0.4

---

requirements.txt

Update to Django 1.11.15

---

charcoallog/core/scrap_line3_service.py

Fix regrex for ipca web scrapping

---

charcoallog/investments/templates/investments/frameset_pages/line3.html

Fix basic_data in line3.html - investments

---

charcoallog/investments/templates/investments/detail.html

Fix item attr in detail.html

---

charcoallog/investments/templates/investments/frameset_pages/form2.html
charcoallog/investments/tests/test_home_html.py

Add date fields form2 - investments

---

charcoallog/investments/serializers.py
charcoallog/investments/static/ajax_vue.js
charcoallog/investments/templates/investments/frameset_pages/line3.html
charcoallog/investments/templates/investments/home.html
charcoallog/investments/tests/test_put_del_apiview.py
charcoallog/investments/urls.py

JS to work with DRF - investments

---

charcoallog/investments/signals.py
charcoallog/investments/tests/test_model_create.py

Signal from bank delete investment

---

charcoallog/investments/templates/investments/detail.html
charcoallog/investments/tests/test_investment_detail.py

fix investments detail html page

---

charcoallog/investments/signals.py

Use .first() to make sure one record will be deleted

---

charcoallog/bank/post_service.py
charcoallog/bank/tests/test_post_service.py

Transfer and Schedule working together

---

charcoallog/bank/post_service.py

Separate Transfer between accounts from MethodPost

---

charcoallog/bank/post_service.py

Dict instead of class to transfer/schedule records

---

charcoallog/investments/static/ajax_vue_for_details.js
charcoallog/investments/templates/investments/detail.html
charcoallog/investments/tests/test_investment_detail.py

Invest Detail with js. Skeleton

---

charcoallog/investments/tests/test_home_html.py

Check investments/home.html tests

---

charcoallog/investments/serializers.py
charcoallog/investments/static/ajax_vue_for_details.js
charcoallog/investments/templates/investments/detail.html
charcoallog/investments/tests/test_put_del_apiview.py
charcoallog/investments/urls.py
charcoallog/investments/views.py

Implement API for JS - details

---

charcoallog/investments/tests/test_put_del_apiview.py

Clean test_put_del_apiview

---

charcoallog/investments/detail_post_service.py
charcoallog/investments/tests/test_detail_post_service.py
charcoallog/investments/views.py

POST in detail view must be refactored and need tests

---

charcoallog/investments/models.py
charcoallog/investments/service.py

Attach select_related to user_logged

---

charcoallog/investments/brief_investment_service.py
charcoallog/investments/models.py
charcoallog/investments/tests/test_brief_investment.py

QuerySet total with keyword

---

charcoallog/investments/brief_investment_service.py
charcoallog/investments/templates/investments/frameset_pages/line1.html
charcoallog/investments/tests/test_brief_investment.py
charcoallog/investments/tests/test_line1_service.py

Fix kind_investment method name

---

charcoallog/bank/models.py
charcoallog/investments/models.py

.as_manager() instead of .from_queryset

---

.flake8
charcoallog/bank/tests/test_view_delete.py
charcoallog/bank/tests/test_view_update.py
charcoallog/core/tests/test_home_context.py
charcoallog/investments/service.py
charcoallog/investments/tests/test_line1_service.py
charcoallog/investments/tests/test_model_create.py

max-line-length=100

---

charcoallog/bank/templates/bank/frameset_pages/form1.html
charcoallog/bank/tests/test_home_context.py
charcoallog/investments/static/ajax_vue_for_details.js
charcoallog/investments/templates/investments/detail_frameset/detail_form1.html
charcoallog/investments/templates/investments/frameset_pages/form1.html
charcoallog/investments/tests/test_home_html.py
charcoallog/investments/tests/test_investment_detail.py

Money step - four forms

---

charcoallog/investments/static/ajax_vue_for_details.js
charcoallog/investments/tests/test_put_del_apiview.py
charcoallog/investments/views.py

Details do not delete

---

charcoallog/investments/signals.py

Invest Signals should delete based on date, money, kind only

---

charcoallog/investments/signals.py
charcoallog/investments/tests/test_model_create.py
charcoallog/investments/tests/test_post_service.py
charcoallog/investments/views.py

Clean select_related mess

---

charcoallog/bank/__init__.py
charcoallog/bank/apps.py
charcoallog/bank/signals.py
charcoallog/bank/tests/test_transfer_to_bank.py
charcoallog/investments/__init__.py
charcoallog/investments/apps.py
charcoallog/investments/signals.py

signals that deals with bank models in bank app

---

charcoallog/core/service.py
charcoallog/core/templates/core/frameset_pages/line2.html
charcoallog/core/tests/test_service.py

Invest info in core app

---

requirements-dev.txt

Update flake8 and pycodestyle

---

charcoallog/core/scrap_line3_service.py
charcoallog/core/tests/ipca.html
charcoallog/core/tests/test_scraping_bs4_line3.py

Fix ipca regex

---

charcoallog/accounts/urls.py
charcoallog/bank/get_service.py
charcoallog/bank/models.py
charcoallog/bank/post_service.py
charcoallog/bank/signals.py
charcoallog/bank/tasks.py
charcoallog/bank/views.py
charcoallog/core/tasks.py
charcoallog/investments/templates/investments/detail.html
charcoallog/investments/tests/test_investment_detail.py
charcoallog/investments/views.py

Fix some pylint

---

charcoallog/bank/templates/bank/frameset_pages/line3.html
charcoallog/bank/tests/test_home_context.py
charcoallog/bank/views.py
charcoallog/investments/service.py
charcoallog/investments/templates/investments/newinvestmentdetails_detail.html
charcoallog/investments/tests/test_investment_detail.py
charcoallog/investments/tests/test_service.py
charcoallog/investments/urls.py
charcoallog/investments/views.py

Use Django convention to maybe use CBV with easy

---

charcoallog/settings.py
requirements.txt

Install django-celery-beat

---

charcoallog/accounts/urls.py
charcoallog/bank/urls.py
charcoallog/core/urls.py
charcoallog/investments/urls.py
charcoallog/urls.py
requirements.txt

2.0.0 urls

---

.flake8
.isort.cfg
charcoallog/core/templates/core/frameset_pages/line2.html
charcoallog/investments/static/ajax_vue.js
charcoallog/investments/static/ajax_vue_for_details.js
charcoallog/investments/urls.py
charcoallog/investments/views.py

fix path in core,
new conf for flake8 and isort
close #206

api delete returns nothing,

---

charcoallog/core/templates/core/frameset_pages/line2.html
charcoallog/investments/templates/investments/frameset_pages/line1.html
charcoallog/investments/tests/test_investment_detail.py
charcoallog/investments/tests/test_put_del_apiview.py
charcoallog/investments/urls.py

investments urls
